config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'conference' => 'static_pages#conference'

  get 'leadership' => 'static_pages#leadership'

  get 'registration' => 'static_pages#registration'

  get 'contactus' => 'static_pages#contactus'
  
  get 'tourinfo' => 'static_pages#tourinfo'
  
  get 'aboutus' => 'static_pages#aboutus'
  
  get 'committees' => 'static_pages#committees'
  
  get 'location' => 'static_pages#location'
    
  get 'schedule' => 'static_pages#schedule'
  
  get 'secretarygeneral' => 'static_pages#secretarygeneral'
  
  get 'deputysecretarygeneral' => 'static_pages#deputysecretarygeneral'
  
  get 'admin' => 'static_pages#admin'
  
  get 'tech' => 'static_pages#tech'
  
  get 'chairapps' => 'static_pages#chairapps'
  
  get 'school' => 'static_pages#school'
  
  get 'banking'=> 'static_pages#banking'
  
  get 'teacherrecs' => 'static_pages#teacherrecs'
  
  get 'hotel' => 'static_pages#hotel'
  
  get 'schoolregis' => 'static_pages#schoolregis'
  
  get 'ga1' => 'static_pages#ga1'
  
  get 'ga2' => 'static_pages#ga2'
  
  get 'ecosoc1' => 'static_pages#ecosoc1'
  
  get 'ecosoc2' => 'static_pages#ecosoc2'
  
  get 'hrc1' => 'static_pages#hrc1'
  
  get 'hrc2' => 'static_pages#hrc2'
  
  get 'ec' => 'static_pages#ec'
  
  get 'spc' => 'static_pages#spc'
  
  get 'spt' => 'static_pages#spt'
  
  get 'ap' => 'static_pages#ap'
  
  get 'disarm' => 'static_pages#disarm'
  
  get 'sc' => 'static_pages#sc'
  
  get 'icj' => 'static_pages#icj'
  
  get 'hissc' => 'static_pages#hissc'
  
  get 'icjregistration' => 'static_pages#icjregistration'
  
  get 'transportation' => 'static_pages#transportation'
  
  get 'photos' => 'static_pages#photos'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def conference
  end

  def leadership
  end

  def registration
  end

  def contactus
  end
  
  def aboutus
  end
  
  def committees
  end
  
  def schedule 
  end
  
  def location
  end 
  
  def hotels 
  end 
  
  def tourinfo 
  end 
  
  def secretarygeneral 
  end 
  
  def deputysecretarygeneral
  end
  
  def admin
  end
  
  def tech
  end 
  
  def chairapps
  end 
  
  def school 
  end 
  
  def banking 
  end 
  
  def teacherrecs
  end 
  
  def hotels
  end 
  
  def schoolregis
  end 
  
  def ga1
  end 
  
  def ga2
  end 
  
  def ecosoc1
  end 
  
  def ecosoc2
  end 
  
  def hrc1
  end 
  
  def hrc2 
  end 
  
  def ec
  end 
  
  def spc
  end 
  
  def spt
  end 
  
  def ap 
  end 
  
  def disarm
  end 
  
  def sc 
  end 
  
  def icj
  end 
  
  def hissc
  end 
  
  def icjregistration
  end
  
  def transportation
  end 
  
  def photos
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   Seoul Model United Nations XIX
  </small>
  <nav>
    <ul>
      <small>
      <li><%= link_to "Contact", contactus_path %></li>
      <li><a href="http://news.railstutorial.org/">Facebook</a></li>
      </small>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    
  <head>
<%= favicon_link_tag %> 
    <title><%= yield(:title) %> Seoul Model United Nations</title>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
  </head>
  <body>
    <%= yield %>
  </body>
   <head>
  <body>
 <header class="navbar navbar-fixed-top navbar-inverse">
            <div class="container">
          <%= link_to "SEOMUN", root_path, id: "logo" %>
                
                <nav>
                    
      <ul class="nav navbar-nav navbar-right">
           <li><%= link_to "HOME", root_path %></li>
          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              CONFERENCE <b class="caret"></b>
                              </a>
                             <ul class="dropdown-menu">
                                  <li><%= link_to "About us", aboutus_path %></li>
                                  
                                   <li><%= link_to "Schedule", schedule_path %></li>
                                   <li><%= link_to "Venue", location_path %></li>
                                   <li><%= link_to "Hotel", hotel_path %></li>
                                  <li><%= link_to "Tour Info", tourinfo_path %></li>
                                  <li><%= link_to "Transportation", transportation_path %></li>
                                  <li><%= link_to "Photos and Videos", photos_path %></li>
                                  <li><%= link_to "Contact Us", contactus_path %></li>
                                  
                        </li>
                        </ul> 
                
          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              LEADERSHIP <b class="caret"></b>
                              </a>
                             <ul class="dropdown-menu">
                                  <li><%= link_to "Secretary General", secretarygeneral_path %></li>
                                   <li><%= link_to "Deputy Secretary Generals", deputysecretarygeneral_path %></li>
                                   <li><%= link_to "Administrative Director", admin_path %></li>
                                   <li><%= link_to "Technology Directors", tech_path %></li>
                                  
                        </li>
                        </ul> 
                       <li class="dropdown">
                             <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              COMMITTEES <b class="caret"></b>
                              </a>
                             <ul class="dropdown-menu">
                                  <li><%= link_to "General Assembly 1", ga1_path %></li>
                                   <li><%= link_to "General Assembly 2", ga2_path %></li>
                                   <li><%= link_to "ECOSOC I", ecosoc1_path %></li>
                                   <li><%= link_to "ECOSOC II", ecosoc2_path %></li>
                                   <li><%= link_to "Human Rights Council I", hrc1_path %></li>
                                   <li><%= link_to "Human Rights Council II", hrc2_path %></li>
                                   <li><%= link_to "Environmental Commission", ec_path %></li>
                                   <li><%= link_to "Special Conference", spc_path %></li>
                                   <li><%= link_to "Six Party Talks", spt_path %></li>
                                   <li><%= link_to "Advisory Panel", ap_path %></li>
                                   <li><%= link_to "Disarmament Commission", disarm_path %></li>
                                   <li><%= link_to "Security Council", sc_path %></li>
                                   <li><%= link_to "ICJ", icj_path %></li>
                                   <li><%= link_to "Historical Security Council", hissc_path %></li>
                           
                       </li>
                       </ul>
                        <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              REGISTRATION <b class="caret"></b>
                              </a>
                             <ul class="dropdown-menu">
                                 <li><%= link_to "Invitation",    school_path %></li>
                                 <li><%= link_to "School Registration",    schoolregis_path %></li>
                                 <li><%= link_to "Banking",    banking_path %></li>
                                   <li><%= link_to "ICJ Registration",    icjregistration_path %></li>
                       <li><%= link_to "Officer Applications",    chairapps_path %></li>
                       
                                  
                        </li>
                        </ul> 
                  
                     
                       
    </ul>    
    
     </nav>                 
     </div>
     
     </header>
 
      

        
        </body>
        
</html>

app/views/static_pages/aboutus.html.erb
<div class="jumbotron" >

</div>


<div class="container-fluid text-center">
<div class="homepageimage">
<img align="middle" alt="Rails logo" src="/assets/conferencepages.jpg"  />
</div>
<h1>About Us </h1>
<div class="homepagetext text-center"> 
<p>The Seoul Model United Nations (SEOMUN) conference is a student-led, three-day simulation of the United Nations for high school students around the world. Organised by international schools in Korea, SEOMUN is now holding its 19th session and we are expecting over 600 participants.

This year’s conference will be hosted by Seoul Foreign School, held at the KINTEX Convention & Exhibition Centre. Please note that only school registrations will be accepted - all participants must be current students at a registered school.

The deadline for school registration and officer applications is June 1st 2016. Delegate registration will be due on September 15th 2016. 

We look forward to seeing you in November. More information will be updated soon. </p>
</div>
</div>

app/views/static_pages/admin.html.erb
<div class="jumbotron" >

</div>
<div class="container-fluid">
    <div class="committeeheader text-center">
    <h1>Administrative Director Hyong Min Kim</h1>
    </div>
<div class="admintext">
    <img class="adminphoto" alt="Rails logo" src="/assets/hyong.JPG"  vspace="35" hspace="30" align="right" />
     <div class="homepagetext">
    Honourable Delegates, Distinguished Student Officers, and Esteemed Advisors,
 
<p>I am Hyong Min Kim, currently a junior at Seoul Foreign School. It is my great honor to serve you as Administrative Director for SEOMUN XIX. My duty is to oversee logistical support for the conference, including distribution of supplies, room assignment and setting, provision of equipment, and much more. It is a daunting task, yet a responsibility I am proud and privileged to assume.</p>

<p>My MUN career began in 6th Grade – like most others, in a crowded General Assembly as a clumsy novice delegate. I still remember the stunning awe I felt in my first conference as I saw the United Nations, something I had hitherto seen only on the news, being unfolded before my eyes so naturally yet professionally. Even after participating in more than fifteen conference throughout the span of five years, MUN never ceases to amaze me. In particular, I am constantly amazed by how quickly cultural and ethnical barriers between delegates disappear as they engage in debate with people whom they have never met before. Over a span of a few days, complete strangers become cherished comrades as they find common grounds and cooperate for successful resolutions of the issues at hand.</p>

<p>SEOMUN is a conference where such things can and will happen. It reflects cohesive variety, attracting schools from all over the world and effectively uniting them under the banners of common progression and welfare of mankind. Of all the conferences I have attended over my five years of MUN career, SEOMUN is decidedly a conference that I believe truly exemplifies the meaning of diversity – hence this year’s theme, Embracing Diversity.</p>

<p>As an avid MUNer and passionate proponent of SEOMUN, I very much look forward to this conference. Whether you are a novice or a veteran, a delegate or a student officer, I have no doubt that SEOMUN XIX will be a thrilling, rewarding, unforgettable experience for you.</p>
 
<p>Warmly,</p>
<p>Hyong Min Kim</p>
<p>Administrative Director</p>
<p>Seoul Foreign School ‘18</p>
<p>hyongmin.kim.18@seoulforeign.org</p>
    <hr>
    </div>
    </div>
    </div>

app/views/static_pages/contactus.html.erb
<div class="jumbotron" >

</div>
<div class="container-fluid">
     <div class="homepageimage">
    <img alt="Rails logo" src="/assets/contactus.jpg"  />
    </div>
      <div class="committeeheader text-center">
<h1>Contact us</h1>
</div>
<div class="homepagetext">
<p>If you have any questions or concerns please write to us at mun@seoulforeign.org. We will do our best to help you.</p>
</div>
</div>

app/views/static_pages/disarm.html.erb
<div class="jumbotron" >

</div>
<div class="container-fluid">
    <div class="homepageimage">
    <img alt="Rails logo" src="/assets/DISARMAMENTCOMMISION.jpg" width="100%"  />
        </div>
    <div class="committeeheader text-center">
<h1>Topics</h1>
</div>
<div class="homepagetext">
<p>
    <ol>
        <li><%= link_to "Measures to prevent terrorists from obtaining weapons of mass destruction", "/DIS-AP-SeiChang-1.docx/#{@bl_file}" %></li>
        <li><%= link_to "Regulating the use of Unmanned Aerial Vehicles (UAV) in armed conflicts and peacekeeping missions", "/DIS-­DAP­-AmyKang-2.docx/#{@bl_file}" %></li>
        <li><%= link_to "Increasing transparency and alleviating tensions arising from arms race in outer space", "/DIS-P-SewonPriscillaChang-3.docx/#{@bl_file}" %></li>
    </ol>
</p>
<hr>
</div>
<div class="committeeheader text-center">
<h1>President's Address</h1>
</div>
<div class="homepagetext">

<img class="secgenphoto" alt="Rails logo" src="/assets/D-P.png" width="300"align="right" vspace="10" hspace="30"  />

<p>Delegates, Student Officers and Guests: </p>

<p>Welcome to the Disarmament Commission of the nineteenth SEOMUN! I am Sewon Priscilla Chang, and senior attending Seoul Foreign School. It is my greatest pleasure to meet you all at my third and last SEOMUN conference. </p>

<p>Disarmament is a pressing issue to be debated upon in the twenty-first century. The rise of terrorist groups, frequently occurring attacks, and constant tensions between countries. As technology used in weapons continue to develop and advance day by day, such conflicts await us, and the importance of disarmament increases. </p>

<p>As delegates of the Disarmament Commission, you will debate on issues regarding preventing terrorists from obtaining weapons of mass destruction, regulating the use of Unmanned Aerial Vehicles (UAV) in armed conflicts and peacekeeping missions, and increasing transparency and alleviating tensions arising from arms race in outer space. While researching and debating on the issues, it is imperative for you to keep in mind that in order for nations to trust each other, governments should keep their promises of transparency and reduction of threatening weaponry. </p>

<p>One piece of advice that I would like to leave you is to stay away from hesitation. SEOMUN XIX can give you the opportunity to practice basic interaction and negotiation skills with new people. So do not be hesitant to show your unique potential and try new things. Everything you do will build up to become a part of the stairs to success. </p>

<p>I hope you all have a splendid conference experience full of memories to cherish. What’s most important in any conference is enjoying it, so do anything and everything you can to make SEOMUN XIX another, if not your first memorable one!</p>

<p>Wishing you the best of luck,</p>

<p>Sewon Priscilla Chang</p>

<p>President of Disarmament Committee</p>

<p>Seoul Foreign School ‘17</p>

<p>sewon.chang.17@seoulforeign.org</p>






<hr>

</div>
<div class="committeeheader text-center">
<h1>Student Officers</h1>
</div>


  <div class="col-md-6">
      <figure><img class="secgenphoto" alt="Rails logo" src="/assets/D-AP.jpg" width="240" height="300" vspace="10" hspace="95"  /><figcaption>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Assistant President <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sei Chang</p></figcaption></figure>
      </div>
  <div class="col-md-6">
    <figure><img class="secgenphoto" alt="Rails logo" src="/assets/D-DAP.png" width="240" height="300" vspace="10" hspace="95"  /><figcaption>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deputy Assistant President <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Shinyi (Amy) Kang</p></figcaption></figure>
  </div>
  
</div>
</div>

app/views/static_pages/ga2.html.erb
<div class="jumbotron" >

</div>
<div class="container-fluid">
    <div class="homepageimage">
    <img alt="Rails logo" src="/assets/GENERAL ASSEMBLY 2.jpg" width="100%"  />
    </div>
    <div class="committeeheader text-center">
<h1>Topics</h1>
</div>
<div class="homepagetext">
<p>
    <ol>
        <li><%= link_to "Reforming fiscal and international assistance to ensure sustainable development in LEDCs", "/GA2-P-YumiMunKim-1.docx/#{@bl_file}" %></li>
        <li><%= link_to "Improving urban management plans to encourage demographic diversity", "/GA2-AP-JungWon(JD)Choi-2.docx/#{@bl_file}" %></li>
        <li><%= link_to "Measures to balance intra-governmental data security and transparency", "/GA2-DAP-AndyHan-3.docx/#{@bl_file}" %></li>
        <li><%= link_to "Combating social prejudice against migrant workers", "/GA2-DAP-AngelaWang-4.docx/#{@bl_file}" %></li>
    </ol>
</p>
<hr>
</div>
<div class="committeeheader text-center">
<h1>President's Address</h1>
</div>
<div class="homepagetext">

<img class="secgenphoto" alt="Rails logo" src="/assets/GAII-P.jpg" width="300"align="right" vspace="10" hspace="30"  />

<p>Delegates, Student Officers and Guests:</p>

<p>Welcome to the General Assembly II of SEOMUN XIX. My name is Yumi Mun Kim and I am a current senior attending Korea International School. It is my utmost honor to serve as your President at this year’s SEOMUN conference. </p>

<p>Exactly two SEOMUN conferences ago, I was sitting in your seat staring at the General Assembly’s agendas, wondering what in the world half of the words meant, and attempting to figure out how the Russian Federation was even related to the issue at hand. But three General Assemblies later, I have unearthed the beauty in this representing organ of the United Nations. The General Assembly strives for equity of treatment towards all participating bodies as it is the sole committee in which equal representation is offered. The resolutions that are passed in the UNGA may not have binding force among member nations, but have a greater value and voice that spark action across the world. At this year's conference, delegates will be expected to tackle four of the most pressing issues of the modern day world that encompasses the economy, society, politics, and last but not least, the environment.<p>

<p>Whether you are a newbie delegate who is still uncomfortable referring to yourself as "this delegate" or a veteran of 15+ conferences, I hope that during your attendance in the General Assembly II at this year's SEOMUN, you sincerely take on an active role in tackling and resolving the agendas presented and gain something meaningful throughout this experience. </p>

<p>I wish you the best of luck,</p>

<p>Yumi Mun Kim</p>
<p>General Assembly II President</p>
<p>Korea International School, ‘17</p>
<p>ymkim17@student.kis.or.kr</p>

<hr>

</div>
<div class="committeeheader text-center">
<h1>Student Officers</h1>
</div>
<div class="row">
  <div class="col-xs-6 col-md-4"><figure><img class="secgenphoto"  src="/assets/GAII-AP.jpg" width="230" height="300" vspace="10" hspace="27"  /><figcaption>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Assistant President<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jung Won (JD) Choi</p></figcaption></figure></div>
  <div class="col-xs-6 col-md-4"><figure><img class="secgenphoto" alt="Rails logo" src="/assets/GAII-DAP.jpg" width="230"height="300" vspace="10" hspace="27"  /><figcaption>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deputy Assistant President<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sungjun (Andy) Han</p> </figcaption></figure></div>
  <div class="col-xs-6 col-md-4"><img class="secgenphoto" alt="Rails logo" src="/assets/GAII-DAP2.JPG" width="230"height="300" vspace="10" hspace="27"  /><figcaption>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deputy Assistant President<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Angela Wang</p> </figcaption></figure></div>
</div>
</div>

app/views/static_pages/hotel.html.erb
<div class="jumbotron" >

</div>
<div class="container-fluid">
      <div class="homepageimage">
<img alt="Rails logo" src="/assets/mvlgoyang.JPG" width="100%"  />
</div>
<div class="committeeheader text-center">
<h1><p> <a href=http://www.mvlhotel.com/daemyung.mvl.goyang.eng.main.ds/dmparse.dm target="_blank">The MVL Goyang Hotel</a></p> </h1>
</div>
<div class="homepagetext">
<p>By bus, the MVL is located approximately 10 minutes from KINTEX, the conference venue. The hotel is providing special rates for SEOMUN participants and transportation to and from KINTEX. 
 </p>
 <p>The rates are as follows:</p>
 <ul style="list-style-type:none">
 <p><u>Rate without buffet breakfast</u></p>
<li><b>Superior Twin................................................................................121,000KRW     </b></li>
<li><b>Family Twin (Triple Room)...........................................................139,150KRW
</b></li>
<li><b>Superior Double............................................................................121,000KRW</b></li>
</ul>
<ul style="list-style-type:none"> 
 <p><u>Rate with buffet breakfast</u></p>

<li><b>Superior Twin................................................................................164,560KRW</b></li>
<li><b>Family Twin (Triple Room)...........................................................204,490KRW</b></li>
<li><b>Superior Double............................................................................164,560KRW </b></li>
<li>*Buffet breakfast is 21,780KRW per person. </li>
</ul>

  <li>Rates only apply for check-in and check-out from November 23rd to November 27th. 
</li>
  <li>The official check-in time is 15:00 and the check-out time is noon. </li>
  <li>Rates are per room, per night basis.</li>
  <li>Rates include free wifi. 
</li>


<p>Hotel Address: Hotel Address: 20, Taegeuk-ro, Ilsandong-gu, Goyang-si, 10394, Gyeonggi-do, Korea
</p>

</div>
</div>

app/views/static_pages/icjregistration.html.erb
<div class="jumbotron" >

</div>
<div class="container-fluid">
      <div class="homepageimage">
    <img alt="regis" src="/assets/contactus.jpg"   />
    </div>
    
      <div class="committeeheader text-center">
             <h1>International Court of Justice Applications</h1> 
    <p>If you are interested in participating in the International Court of Justice as a judge or as an advocate, please follow the steps below to enter into consideration for these positions. Thank you for your interest. 
</p>
      <h3><u>The chair application process is as follows:</u></h3>
      </div>
  <div class="homepagetext">
 
 <h4><p><b>Step #1 - Fill in the ICJ application using either option #1 or option #2. </b>
</p></h4>

<h4><p><b>&nbsp;&nbsp;&nbsp;&nbsp;Option #1 - If you have access to Google products</b> - Please fill out the <a href="https://docs.google.com/a/seoulforeign.org/forms/d/1YmwB8vn4LRigeIhw34ILUI4-Do_8mk7KPd64g_zFJOY/edit">Google form</a> by September  <p>15th, 2016 11:59PM KST.</p></p>
</p></h4>

<h4><p><b>&nbsp;&nbsp;&nbsp;&nbsp;Option #2 - If you don’t have access to Google Products</b>  - Please download <%= link_to "ICJ Application", "/SEOMUNXIXICJApplication.docx/#{@bl_file}" %> <p> and email the form to seomunxix@gmail.com AND shur18@student.kis.or.kr by September 15th, 2016  <p>11:59PM KST.</p></p> </p></h4>

<h4><p><b>Step #2 - </b> Wait to hear if you have received a position in the International Court of Justice. 
</p></h4>

<h4><p>If you have any questions, please do not hesitate to contact us at seomunxix@gmail.com. </p></h4>





</div>
</div>

app/views/static_pages/leadership.html.erb
<html>
    

</html>

<img src="/assets/backgroundimage.jpg" style='width:100%;height:100%' />

app/views/static_pages/registration.html.erb
<img src="/assets/backgroundimage.jpg" style='width:100%;height:100%' />

app/views/static_pages/schoolregis.html.erb
<div class="jumbotron" >

</div>

<div class="container-fluid">
        <div class="homepageimage">
      <img alt="Rails logo" src="/assets/contactus.jpg" />
      </div>
         <div class="committeeheader text-center">
      <h1>School Registration</h1>
      </div>
         <div class="homepagetext">
      <p><b>Option #1</b> - If you have access to Google products, click this link SEOMUN XIX Registration Form I</a> and complete the form.</p>
      <p><b>Option #2</b> - If you do not have access to Google products please answer the following questions and send it to mun@seoulforeign.org. </p>
<li><b>1) 	School Name</b></li>
<li><b>2) 	School’s Country</b></li>
<li><b>3) 	MUN Director Name</b></li>
<li><b>4) 	MUN Director Email Address</b></li>
<li><b>5) 	Additional Email Addresses (If you want other directors/chaperones to receive updates)</b></li>
<li><b>6) 	Number of delegates you would like to attend</b></li>
<li><b>7) 	Do you desire any SC Positions (Yes/No)</b></li>
<li><b>8) 	Do you desire any ICJ Positions (Yes/No)</b></li>
 
<p>After you have completed either option all you need to do is wait to receive your formal invitation to SEOMUN XIX.  We will do our best to accommodate your requested number of delegates. </p>
</div>
</div>